/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SurveyIdPanel.java
 *
 * Created on Sep 28, 2011, 5:56:24 PM
 */
package edu.asu.commons.foraging.ui;

/**
 *
 * @author alllee
 */
public class SurveyIdPanel extends javax.swing.JPanel {

    /** Creates new form SurveyIdPanel */
    public SurveyIdPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        surveyIdInstructionsLabel = new javax.swing.JLabel();
        surveyIdTextField = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        participantIdLabel = new javax.swing.JLabel();

        surveyIdInstructionsLabel.setText("Please enter a unique survey ID for this participant:");

        surveyIdTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surveyIdTextFieldActionPerformed(evt);
            }
        });

        submitButton.setText("Submit");

        participantIdLabel.setText("Participant ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(surveyIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(surveyIdInstructionsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                        .addComponent(participantIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(submitButton))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(surveyIdInstructionsLabel)
                    .addComponent(participantIdLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(surveyIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(submitButton)
                .addContainerGap(256, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void surveyIdTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surveyIdTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_surveyIdTextFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel participantIdLabel;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel surveyIdInstructionsLabel;
    private javax.swing.JTextField surveyIdTextField;
    // End of variables declaration//GEN-END:variables
}
