package edu.asu.commons.foraging.ui;

import javax.swing.JOptionPane;
import javax.swing.JPanel;

import edu.asu.commons.foraging.client.ForagingClient;

/**
 * $Id: Exp$
 * 
 * @author Allen Lee
 */
public class SurveyIdPanel extends JPanel {
    
    private static final long serialVersionUID = -5354746936864584226L;
    public final static String NAME = "survey id panel";
    
    private ForagingClient client;

    /** Creates new form SurveyIdPanel */
    public SurveyIdPanel() {
        initComponents();
        setName(NAME);
    }
    
    public SurveyIdPanel(ForagingClient client) {
        this();
        this.client = client;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        surveyIdInstructionsLabel = new javax.swing.JLabel();
        surveyIdTextField = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        participantIdLabel = new javax.swing.JLabel();

        surveyIdInstructionsLabel.setText("Please enter a unique survey ID for this participant:");

        surveyIdTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surveyIdTextFieldActionPerformed(evt);
            }
        });

        submitButton.setText("Submit");

        participantIdLabel.setText("Participant ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(surveyIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(surveyIdInstructionsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                        .addComponent(participantIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(submitButton))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(surveyIdInstructionsLabel)
                    .addComponent(participantIdLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(surveyIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(submitButton)
                .addContainerGap(256, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void surveyIdTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surveyIdTextFieldActionPerformed
        String surveyId = surveyIdTextField.getText();
        if (surveyId == null || surveyId.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a survey id.");
            return;
        }
        client.sendSurveyId(surveyId);
        

    }//GEN-LAST:event_surveyIdTextFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel participantIdLabel;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel surveyIdInstructionsLabel;
    private javax.swing.JTextField surveyIdTextField;
    // End of variables declaration//GEN-END:variables
}
