/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VotingForm.java
 *
 * Created on Sep 29, 2011, 3:52:52 AM
 */
package edu.asu.commons.foraging.ui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;

import javax.swing.ButtonModel;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

import edu.asu.commons.foraging.client.ForagingClient;
import edu.asu.commons.foraging.event.RuleVoteRequest;
import edu.asu.commons.foraging.rules.ForagingRule;

/**
 *
 * @author alllee
 */
public class VotingForm extends javax.swing.JPanel {
    
    private static final long serialVersionUID = 3871660663519284024L;

    public final static String NAME = "Voting form";
    
    private ForagingClient client;
    
    private List<JRadioButton> radioButtons = new ArrayList<JRadioButton>();
    private List<JLabel> labels = new ArrayList<JLabel>();

    public VotingForm(ForagingClient client) {
        this.client = client;
        initComponents();
        initForm(ForagingRule.values());
        setName(NAME);
    }
    
    private void initForm(ForagingRule... rules) {
        GroupLayout groupLayout = new GroupLayout(this);
        setLayout(groupLayout);
        groupLayout.setAutoCreateGaps(true);
        groupLayout.setAutoCreateContainerGaps(true);
        GroupLayout.SequentialGroup horizontalGroup = groupLayout.createSequentialGroup();
        // horizontal parallel group
        GroupLayout.ParallelGroup horizontalLabelParallelGroup = groupLayout.createParallelGroup();
        horizontalGroup.addGroup(horizontalLabelParallelGroup);
        GroupLayout.ParallelGroup horizontalButtonParallelGroup = groupLayout.createParallelGroup();
        horizontalGroup.addGroup(horizontalButtonParallelGroup);
        
        GroupLayout.SequentialGroup verticalGroup = groupLayout.createSequentialGroup();
        JLabel buttonHeaderLabel = new JLabel("Select one");
        buttonHeaderLabel.setFont(ForagingInterface.DEFAULT_BOLD_FONT);
        horizontalButtonParallelGroup.addComponent(buttonHeaderLabel);
        
        JLabel ruleHeaderLabel = new JLabel("Rule");
        ruleHeaderLabel.setFont(ForagingInterface.DEFAULT_BOLD_FONT);
        horizontalLabelParallelGroup.addComponent(ruleHeaderLabel);
        
        verticalGroup.addGroup(groupLayout.createParallelGroup(Alignment.BASELINE).addComponent(ruleHeaderLabel).addGap(10).addComponent(buttonHeaderLabel));
        
        for (ForagingRule rule: rules) {
            JRadioButton radioButton = new JRadioButton();                        
            radioButton.setActionCommand(rule.name());
            radioButtons.add(radioButton);
            horizontalButtonParallelGroup.addComponent(radioButton);
            JLabel ruleLabel = new JLabel(String.format("%d. %s", radioButtons.size(), rule));
            ruleLabel.setFont(ForagingInterface.DEFAULT_PLAIN_FONT);
            labels.add(ruleLabel);
            buttonGroup.add(radioButton);
            horizontalLabelParallelGroup.addComponent(ruleLabel);
            verticalGroup.addGroup(groupLayout.createParallelGroup(Alignment.BASELINE).addComponent(ruleLabel).addComponent(radioButton));
        }
        JButton submitButton = getSubmitButton();
        horizontalLabelParallelGroup.addComponent(submitButton);
        verticalGroup.addGroup(groupLayout.createParallelGroup(Alignment.BASELINE).addComponent(submitButton).addGap(80));
        groupLayout.setHorizontalGroup(horizontalGroup);
        groupLayout.setVerticalGroup(verticalGroup);
    }
    
    private JButton getSubmitButton() {
        JButton submitButton = new JButton("Submit");
        submitButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                ButtonModel model = buttonGroup.getSelection();
                if (model == null) {
                    JOptionPane.showMessageDialog(VotingForm.this, "Please select a rule.");
                    return;
                }
                ForagingRule selectedRule = ForagingRule.valueOf(model.getActionCommand());
                client.transmit(new RuleVoteRequest(client.getId(), selectedRule));
            }
        });
        return submitButton;
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        buttonGroup = new javax.swing.ButtonGroup();
    }// </editor-fold>//GEN-END:initComponents

    private javax.swing.ButtonGroup buttonGroup;
    
    public static void main(String[] args) {
        JFrame frame = new JFrame();
        frame.add(new VotingForm(null));
        frame.pack();
        frame.setVisible(true);
        
    }
}
