/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VotingForm.java
 *
 * Created on Sep 29, 2011, 3:52:52 AM
 */
package edu.asu.commons.foraging.ui;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;

/**
 *
 * @author alllee
 */
public class VotingForm extends javax.swing.JPanel {

    List<JRadioButton> radioButtons = new ArrayList<JRadioButton>();
    List<JLabel> labels = new ArrayList<JLabel>();
    /** Creates new form VotingForm */
    public VotingForm() {
        this(Arrays.asList("Rule 1", "Rule 2", "Rule 3", "Rule 4"));
    }
    
    public VotingForm(List<String> rules) {
        initForm(rules);
        initComponents();
    }
    
    private void initForm(List<String> rules) {
        JPanel panel = new JPanel();
        GroupLayout groupLayout = new GroupLayout(panel);
        panel.setLayout(groupLayout);
        groupLayout.setAutoCreateGaps(true);
        groupLayout.setAutoCreateContainerGaps(true);
        GroupLayout.SequentialGroup horizontalGroup = groupLayout.createSequentialGroup();
        // horizontal parallel group
        GroupLayout.ParallelGroup horizontalLabelParallelGroup = groupLayout.createParallelGroup();
        horizontalGroup.addGroup(horizontalLabelParallelGroup);
        GroupLayout.ParallelGroup horizontalButtonParallelGroup = groupLayout.createParallelGroup();
        horizontalGroup.addGroup(horizontalButtonParallelGroup);
        
        GroupLayout.SequentialGroup verticalGroup = groupLayout.createSequentialGroup();

        for (String rule: rules) {
            JRadioButton radioButton = new JRadioButton();                        
            radioButton.setActionCommand(String.valueOf(radioButtons.size()));
            radioButtons.add(radioButton);
            horizontalButtonParallelGroup.addComponent(radioButton);
            JLabel ruleLabel = new JLabel(rule);
            ruleLabel.setFont(ForagingInterface.DEFAULT_PLAIN_FONT);
            labels.add(ruleLabel);
            buttonGroup.add(radioButton);
            horizontalLabelParallelGroup.addComponent(ruleLabel);
            verticalGroup.addGroup(groupLayout.createParallelGroup(Alignment.BASELINE).addComponent(ruleLabel).addComponent(radioButton));
        }
        groupLayout.setHorizontalGroup(horizontalGroup);
        groupLayout.setVerticalGroup(verticalGroup);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 469, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    // End of variables declaration//GEN-END:variables
}
